### ISSUE TITLE
how to change data-min and data-max dynamically?

### ISSUE THREAD

**Issue by ilievZlatko** [vsn4ik/input-spinner#26]
Hello, is there any possible way to change dynamically data-min and data-max? I need it now and I see I can only change the step.

**Comment by cobcmw** [comment]
@ilievZlatko So , has your problem been solved?

**Comment by 7iomka** [comment]
@aitlp how to do this?

**Comment by xixilive** [comment]
Unfortunately, you can't change the options of a spinner plugin instance.
But, you can re-render your DOM and setup a new spinner plugin for it.
Also, you can fork this repo.
