### ISSUE TITLE
Potential memory leak when removing elements from the DOM

### ISSUE THREAD

**Issue by samwatkinson1** [vsn4ik/input-spinner#40]
During testing, I've noticed that Chrome memory heap dumps show that when spinners are added then removed from the DOM their events leak and persist in the memory. This can cause slow downs over time in older browsers, e.g. IE11. 

I tested this by adding 1000 individual instances of the spinners to the DOM then removing them with the jQuery .remove() method. The heap stack then shows thousands of instances of Detached elements, e.g. 2000 of those being HTMLDivElements that are still bound to a "mouseup" event.

I think this can be solved by adding a form of a destroy event that will handle purging event handlers.

**Comment by vsn4ik** [comment]
Fixed in #41
